name: escape_your_study_room
description: A short student wellbeing movement-break prototype.
publish_to: none
version: 0.1.0+1

environment:
  sdk: '>=3.8.0 <4.0.0'
  flutter: '>=3.32.0'

dependencies:
  flutter:
    sdk: flutter
  sensors_plus: 7.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
